deploy:
  provider: heroku
  secure: ORQF4O8SVqkqkmoWnUFkUHhpDZx7E2kVx3PXJdqDn6R5HgTMGLLdRBfyMGneJSUtwJO0hB7Txj7QIsQZvqme2klCtFsJTBIeKQ4NiLUHbmNLZOmQ6HjMtNArfRi4Aws4GfKcwqiVLgs3ysigtFJZP0H5hqGP0fKicmv4hTc3FKk=
language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
