deploy:
  provider: heroku
  secure: Pug4VHOtIxpKgF1yaoumWspGh1DS1wgcdw3+iq5MJRYA7o4tFi2n6ZnE9jygXJ2OhpsTuNJhgDbJcAyQLRtW6SZeJi0Ih+m8vLbWqyTHLk6/x0FMntVDTjuNs2w44K8dk9KgX80V5dOULJZHJoCxSAidMGzh9NCqXs5X/kgEi58=
language: java
jdk:
- oraclejdk7
- openjdk7
- openjdk6
